### ISSUE TITLE
support conversion to Python3

### ISSUE THREAD

**Issue by petri** [belvedere-trading/pywinservicemanager#3]
Looks like does not work... :(

**Comment by belvedere-trading-user** [comment]
Hi there. Could you provide a more detailed description of the issue? Thanks.

**Comment by petri** [comment]
... more detailed ...? What do you mean? This is a feature request for Python3 support when I realized the package does not support it, not a bug report.

For example, nosetests fail on Python3, and the example in package README for querying all services fails:

```
  File "Z:\thirdparty\pywinservicemanager\pywinservicemanager\ServiceEntity.py", line 194
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by petri** [comment]
For what it's worth, I took a quick look at the codebase using the 2to3 tool and looks like there's indeed quite a lot of changes required, not all of which are trivial (such that can safely be fixed by the tool) :(

**Comment by petri** [comment]
I let 2to3 munch the package and ran nosetests again. ~~Still 24 failing tests.~~

Update: my bad, I missed some files when doing the conversion. Just one failing test! :)

```
    $ C:\Python36\Scripts\nosetests.exe
..................................................F....................................................................................
======================================================================
FAIL: TestInitWithParametersOfNotValidValue (pywinservicemanager.tests.TestFailureActionConfigurationResetPeriodType.TestFailureActionConfigurationResetPeriodType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Z:\thirdparty\pywinservicemanager\pywinservicemanager\tests\TestFailureActionConfigurationResetPeriodType.py", line 24, in TestInitWithParametersOfNotValidValue
    self.assertRaises(ValueError, FailureActionConfigurationResetPeriodType, int(1))
AssertionError: ValueError not raised by FailureActionConfigurationResetPeriodType

----------------------------------------------------------------------
Ran 135 tests in 2.886s

FAILED (failures=1)

**Comment by petri** [comment]
Question: do you want/need to keep Python2 compatibility?

**Comment by belvedere-trading-user** [comment]
My mistake - I missed the title and thought this was a bug report :)

We do need Python2 compatibility for our internal deployment of this API; however, it probably shouldn't take too much time to make this Python3 compatible. This seems like something we should add.

**Comment by petri** [comment]
Well, given there is (after running 2to3 on the whole package) just one failing test after all (see above nosetests report), I guess this can be considered a bug report just as well ;) Hopefully that isn't hard to fix.

**Comment by petri** [comment]
Ok, it was fairly easy. The test fails ([here](https://github.com/belvedere-trading/pywinservicemanager/blob/master/pywinservicemanager/tests/TestFailureActionConfigurationResetPeriodType.py#L24)) because the automatic 2to3 conversion converts `long(1)` which is used to trigger failure (on purpose), to `int(1)` - which does NOT fail. So perhaps just change `long(1)` to `float(1)` so that it will fail on both Python2 and 3.

**Comment by petri** [comment]
I changed the issue title to request for supporting (successful) 2to3 conversion so we can fix it and then close the issue. I will provide a PR.

**Comment by petri** [comment]
Question: After the PR, how about adding a new Python3 branch with results of 2to3 conversion? So people can download that for Python3 use. It would be nice if you could package it, too, and publish on PyPI, of course...?
